create table if not exists public.releases (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null check (type in ('admin', 'website', 'android', 'ios')),
  date date not null default current_date,
  assigned_tester text not null,
  status text not null default 'new' check (status in ('new', 'testing', 'done')),
  created_at timestamptz not null default now()
);

alter table public.releases enable row level security;
alter publication supabase_realtime add table public.releases;

drop policy if exists "Public can read releases" on public.releases;
create policy "Public can read releases"
on public.releases
for select
to anon
using (true);

drop policy if exists "Public can insert releases" on public.releases;
create policy "Public can insert releases"
on public.releases
for insert
to anon
with check (true);

drop policy if exists "Public can update releases" on public.releases;
create policy "Public can update releases"
on public.releases
for update
to anon
using (true)
with check (true);

drop policy if exists "Public can delete releases" on public.releases;
create policy "Public can delete releases"
on public.releases
for delete
to anon
using (true);

insert into public.releases (title, type, date, assigned_tester, status)
values
  ('[Предрелиз] веб-сайта - 2.2', 'website', '2026-03-04', 'Чураев', 'done'),
  ('[Предрелиз] админки 5.78', 'admin', '2026-03-04', 'Белов', 'done'),
  ('iOS 7.128', 'ios', '2026-03-10', 'Чураев', 'done'),
  ('iOS 7.125 BY', 'ios', '2026-03-11', 'Белов', 'done'),
  ('[Предрелиз] админки 5.79', 'admin', '2026-03-18', 'Беляков', 'done'),
  ('iOS 7.129', 'ios', '2026-03-20', 'Козачук', 'done'),
  ('iOS 7.129', 'ios', '2026-04-02', 'Белов', 'testing'),
  ('[Предрелиз] веб-сайта - 2.3', 'website', '2026-04-02', 'Бутурлин', 'new');
